org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.4
loader_version=0.16.10
loom_version=1.17.17
fabric_api_version=0.119.4+1.21.4
baritone_api_version=1.13.1

mod_version=3.3.0
maven_group=dev.sealedclient
archives_base_name=sealed-client-mc1.21.4
